### ISSUE TITLE
Fix root directory path

### ISSUE THREAD

**Issue by karstenpedersen** [karstenpedersen/obsidian-advanced-random-note#2]
The "/" root directory needs to be identified in this way:

```
Now: 
path:/

Before:
path: /
```
---

I'm actually testing in the new vault, and it's fine. 
But, in my main vault, it doesn't work. 

Tests I've done:
1. Close all other third-party plugins and restart
2. Create a new vault, After installing and testing Advanced Random Notes is complete,
Copy all the note files in the new vault.

In the above cases, as long as my notes exist in the Vault, 
the shortcut keys used to trigger the search rule will be invalid, 
and the following content will appear in the developer tools.

<details>
<summary>---------Copy From Obsidian Devtools---------</summary>

```javascript
[{… }]
0
:
{ included: true, tag: '#Permanent' }
length
:
1
[[Prototype]]
:
Array(0)
plugin: advanced - random - note: 1108
[{… }]
plugin: advanced - random - note: 1108
[{… }]
plugin: advanced - random - note: 1108
[{… }]
plugin: advanced - random - note: 1108
[{… }]
plugin: advanced - random - note: 1108
[{… }]
plugin: advanced - random - note: 1108
[{… }]
plugin: advanced - random - note: 1108
[{… }]
plugin: advanced - random - note: 1108
[{… }]
plugin: advanced - random - note: 1108
[{… }]
plugin: advanced - random - note: 1108
[{… }]
plugin: advanced - random - note: 1108
[{… }]
plugin: advanced - random - note: 1108
[{… }]
plugin: advanced - random - note: 1108
[{… }]
plugin: advanced - random - note: 1108
[{… }]
plugin: advanced - random - note: 1108
[{… }]
plugin: advanced - random - note: 1108
[{… }]
plugin: advanced - random - note: 1030 Uncaught(in promise) TypeError: tags.map is not a function
	at getTagStrings(plugin: advanced - random - note: 1030: 15)
    at Search.checkTagsWithFile(plugin: advanced - random - note: 1100: 32)
    at Search.checkFileToMatchQuery(plugin: advanced - random - note: 1091: 76)
    at eval(plugin: advanced - random - note: 1059: 19)
    at Array.filter(<anonymous>)
		at Search.search (plugin:advanced-random-note:1058:26)
		at AdvancedRandomNote.executeRandomNoteQuery (plugin:advanced-random-note:1309:36)
		at Object.callback (plugin:advanced-random-note:1327:34)
		at P_ (app.js:1:1751153)
		at e.executeCommand (app.js:1:1752666)
```

</details>

The notes hit by the search rule are all in the root directory. 
I use the note link management system, not the folder.

**Comment by karstenpedersen** [comment]
Release [0.0.8](https://github.com/karstenpedersen/obsidian-advanced-random-note/releases/tag/0.0.8) should fix this, as the custom querying regular expressions are updated.

It also enables queries to use regular expressions, which would make this easier.
